language: go
go_import_path: github.com/src-d/metdata-retrieval
go:
  - 1.13.x

env:
  global:
    - PSQL_USER=user
    - PSQL_PWD=password
    - PSQL_DB=ghsync
    - GITHUB_TOKENS=$GITHUB_TOKEN

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/


stages:
  - name: tests
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: test
      name: "Integration tests"
      os: linux
      services: docker
      script:
        # only linux supports docker https://docs.travis-ci.com/user/docker/ => tests with docker skipped programmatically ~ OS
        - docker-compose up -d
        - make ci-script

    - stage: test
      name: "Integration tests"
      os: osx
      script:
        - make test-coverage

    #- stage: test
    #  name: "Integration tests"
    #  os: windows
    #  script:
    #    - run-integration-tests.bat
    # https://docs.travis-ci.com/user/best-practices-security#steps-travis-ci-takes-to-secure-your-data
    # Remove because: The beta Windows support does not obfuscate secure environment variables leaked
    # into the build log. Please keep reading the next section, on how to avoid leaking secrets to build
    # logs

    - stage: release
      name: 'Release to GitHub'
      script:
        - make packages
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file:
          - build/*.tar.gz
        skip_cleanup: true
        on:
          all_branches: true
